import "@styles/globals.css";
import Navbar from "@components/Navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient"/>
        </div>

        <main className="app">
          <Navbar />
          <button>Connect</button>
          {children}
        </main>
      </body>
    </html>
  )
}
